give @s srp:parasitebush_arc
give @s srp:parasitebush_flower1
give @s srp:parasitebush_grass1
give @s srp:parasitebush_grass2
give @s srp:parasitesapling_flowertall
give @s srp:parasitesapling_tree
give @s srp:parasitebush_arc2
give @s srp:null_two
give @s srp:biomeheart
give @s srp:biomepurifier
give @s srp:evolutionlure
give @s srp:evolutionlure1
give @s srp:evolutionlure2
give @s srp:evolutionlure3
give @s srp:evolutionlure4
give @s srp:evolutionlure5
give @s srp:infestedstain
give @s srp:parasiterubble_bone
give @s srp:parasiterubble_stone
give @s srp:parasiterubbledense_biome
give @s srp:parasiterubbledense_colony
give @s srp:parasiterubbledense_wall
give @s srp:parasitestain_feeler
give @s srp:parasiterubbledense_biome_stone
give @s srp:stairs_parasites_bone
give @s srp:flesh_parasitian_stairs
give @s srp:parasites_slab
give @s srp:evolutionlure6
give @s srp:alive_serp
give @s srp:evolutionlure7
give @s srp:alive_serp2
give @s srp:alive_axe
give @s srp:alive_axe2
give @s srp:living_sword
give @s srp:sentient_sword
give @s srp:living_cleaver
give @s srp:sentient_cleaver
give @s srp:core_sammoner
give @s srp:bone_yeloweye
give @s srp:core_eater
give @s srp:bone_evilcrath
give @s srp:longarm_defence_shard
give @s srp:infasted_flash
give @s srp:null
give @s srp:dirty_horses
give @s srp:dried_tendons
give @s srp:infasted_blade_fragment
give @s srp:living_core
give @s srp:vile_shell
give @s srp:bone_strange
give @s srp:small_piece
give @s srp:infasted_once
give @s srp:small_piece_2
give @s srp:evil_once
give @s srp:rot_sigment
give @s srp:essential_sigment
give @s srp:handled_bone_handle
give @s srp:living_bow
give @s srp:sentient_bow
give @s srp:infestedtrunk
give @s srp:parasitetrunk_ball
give @s srp:parasitetrunk_tree
give @s srp:parasitestain_mud
give @s srp:parasitetrunk_plant
give @s srp:infestedrubble
give @s spr:parasitian_dirt
give @s srp:parasiterubble_flesh
give @s srp:parasitestain_flesh
give @s spr:parasitian_notcoplited_colony_structure
